const PRODUCTS = [
  {
    id: 847618708,
    name: "Green Lion Veloura Fragrance Diffuser 22",
    description: "The Green Lion Veloura Fragrance Diffuser has a special and modern design to fill your space with a pleasant aroma. Made from aluminum alloy and PC, it has an 800mAh battery and 8mL capacity, with an amazing 10W of power, providing up to 3 to 4 hours of continuous mist, and spreads the fragrance up to 15 square meters of space. The diffuser also features four spray modes, atmosphere lights, and touch control. These features have made this compact device a favorite among enthusiasts and people who care about life. Specification Material: Aluminum Alloy + PCFragrance Capacity: 8mLRated Power: 10WBattery Capacity: 800mAhWorking Time: 3 to 4 HoursCharging Port: Type-CInput: 5.0V/1ACharging Time: 1.5 HoursArea Coverage: 15m²FeaturesAtmosphere LightsTouch Control15m² Area Coverage4H WorkingType-C Charging0-60 C Temperature",
    base_price: 26.93,
    base_shipping_cost: 0,
    free_shipping: true,
    sku: "GNVLRFRDFBK",
    slug: "green-lion-veloura-fragrance-diffuser",
    brand: "Green Lion",
    status: "active",
    isFeatured: false,
    isOnSale: false,
    requiresShipping: true,
    requiresInventoryTracking: true,
    stock: 21,
    hasVariants: false,
    totalVariantStock: 0,
    lowStockThreshold: 5,
    images: [
      "products_images/GNVLRFRDFBK_Green_Lion_Veloura_Fragrance_Diffuser_1.jpg",
      "products_images/GNVLRFRDFBK_Green_Lion_Veloura_Fragrance_Diffuser_2.jpg"
    ],
    options: {},
    option_images: {},
    variant_images: {},
    option_variants_stock: {},
    option_price_adjustments: {},
    option_shipping_adjustments: {},
    weight: {},
    dimensions: {},
    option_dimension_overrides: {},
    categories: [
      402646794
    ],
    upselling: [],
    crossSelling: [],
    relatedProducts: [],
    createdAt: "2025-06-15T12:46:22.123Z",
    updatedAt: "2025-09-02T06:29:56.947Z",
    availability: "in_stock",
    condition: "new",
    ean: "",
    gtin: "09904781918916",
    keywords: [],
    metaDescription: "",
    metaTitle: "",
    returnPolicy: "",
    scrapedAt: "2025-06-15T12:46:22.125Z",
    sourceUrl: "https://www.greenlion.net/shop/gnvlrfrdfbk-green-lion-veloura-fragrance-diffuser-5007",
    warranty: ""
  }
];