const PRODUCTS = [
    {
        "id": 847618708,
        "name": "Green Lion Veloura Fragrance Diffuser",
        "description": "The Green Lion Veloura Fragrance Diffuser has a special and modern design to fill your space with a pleasant aroma. Made from aluminum alloy and PC, it has an 800mAh battery and 8mL capacity, with an amazing 10W of power, providing up to 3 to 4 hours of continuous mist, and spreads the fragrance up to 15 square meters of space. The diffuser also features four spray modes, atmosphere lights, and touch control. These features have made this compact device a favorite among enthusiasts and people who care about life. Specification Material: Aluminum Alloy + PCFragrance Capacity: 8mLRated Power: 10WBattery Capacity: 800mAhWorking Time: 3 to 4 HoursCharging Port: Type-CInput: 5.0V/1ACharging Time: 1.5 HoursArea Coverage: 15m²FeaturesAtmosphere LightsTouch Control15m² Area Coverage4H WorkingType-C Charging0-60 C Temperature",
        "base_price": 26.93,
        "base_shipping_cost": 0,
        "free_shipping": false,
        "sku": "GNVLRFRDFBK",
        "gtin": "09904781918916",
        "ean": "",
        "slug": "green-lion-veloura-fragrance-diffuser",
        "brand": "Green Lion",
        "rating": 0,
        "reviews_count": 0,
        "status": "active",
        "isFeatured": false,
        "isOnSale": false,
        "requiresShipping": true,
        "requiresInventoryTracking": true,
        "stock": 21,
        "hasVariants": false,
        "totalVariantStock": 0,
        "lowStockThreshold": 5,
        "features": {
            "material": "Aluminum Alloy + PC",
            "fragrance_capacity": "8mL",
            "rated_power": "10W",
            "battery_capacity": "800mAh",
            "working_time": "3 to 4 Hours",
            "charging_port": "Type-C",
            "input": "5.0V/1A",
            "charging_time": "1.5 Hours",
            "area_coverage": "15m²",
            "atmosphere_lights": true,
            "touch_control": true,
            "15m__area_coverage": true,
            "4h_working": true,
            "type_c_charging": true,
            "0_60_c_temperature": true
        },
        "images": [
            "products_images/GNVLRFRDFBK_Green_Lion_Veloura_Fragrance_Diffuser_1.jpg",
            "products_images/GNVLRFRDFBK_Green_Lion_Veloura_Fragrance_Diffuser_2.jpg"
        ],
        "options": {},
        "option_images": {},
        "variant_images": {},
        "option_variants_stock": {},
        "option_price_adjustments": {},
        "option_shipping_adjustments": {},
        "weight": {},
        "dimensions": {},
        "option_dimension_overrides": {},
        "categories": [
            402646794
        ],
        "upselling": [],
        "crossSelling": [],
        "relatedProducts": [],
        "metaTitle": "",
        "metaDescription": "",
        "keywords": [],
        "warranty": "",
        "returnPolicy": "",
        "availability": "in_stock",
        "condition": "new",
        "createdAt": "2025-06-15T12:46:22.123Z",
        "updatedAt": "2025-06-15T12:46:22.125Z",
        "sourceUrl": "https://www.greenlion.net/shop/gnvlrfrdfbk-green-lion-veloura-fragrance-diffuser-5007",
        "scrapedAt": "2025-06-15T12:46:22.125Z"
    },
    {
        "id": 800116820,
        "name": "Green Lion Alps Fragrance Diffuser 130mL - black",
        "description": "The Green Lion Alps Fragrance Diffuser has a professional look and function to fill your space with a pleasant aroma. Made from glass and PC, It has a 200mAh and 130mL capacity, 1.5w power, providing up to 4 hours of continuous mist. The diffuser also features three spray modes, atmosphere lights, and touch control. It has explosion-proof capabilities so that it will not explode if its temperature rises during operation. These features have made this compact device a favorite among enthusiasts and people who care about life.​ Specification Material: Glass + PCOil Capacity: 130 mLRated Power: 1.5 WBattery Capacity: 200 mAhWorking Time: 4 HoursCharging Port: Type-CInput: 5.0 V / 1 ACharging Time: 1 HourArea Coverage: 20 m²FeaturesAtmosphere LightsTouch ControlExplosion Proof4Hrs WorkingType-C Charging0-60C temperature",
        "base_price": 16.05,
        "base_shipping_cost": 0,
        "free_shipping": false,
        "sku": "GNALFRDI130BK",
        "gtin": "09904781918848",
        "ean": "",
        "slug": "green-lion-alps-fragrance-diffuser-130ml-black",
        "brand": "Green Lion",
        "rating": 0,
        "reviews_count": 0,
        "status": "active",
        "isFeatured": false,
        "isOnSale": false,
        "requiresShipping": true,
        "requiresInventoryTracking": true,
        "stock": 24,
        "hasVariants": false,
        "totalVariantStock": 0,
        "lowStockThreshold": 5,
        "features": {
            "material": "Glass + PC",
            "oil_capacity": "130 mL",
            "rated_power": "1.5 W",
            "battery_capacity": "200 mAh",
            "working_time": "4 Hours",
            "charging_port": "Type-C",
            "input": "5.0 V / 1 A",
            "charging_time": "1 Hour",
            "area_coverage": "20 m²",
            "atmosphere_lights": true,
            "touch_control": true,
            "explosion_proof": true,
            "4hrs_working": true,
            "type_c_charging": true,
            "0_60c_temperature": true
        },
        "images": [
            "products_images/GNALFRDI130BK_Green_Lion_Alps_Fragrance_Diffuser_130mL_-_black_1.jpg",
            "products_images/GNALFRDI130BK_Green_Lion_Alps_Fragrance_Diffuser_130mL_-_black_2.jpg"
        ],
        "options": {},
        "option_images": {},
        "variant_images": {},
        "option_variants_stock": {},
        "option_price_adjustments": {},
        "option_shipping_adjustments": {},
        "weight": {},
        "dimensions": {},
        "option_dimension_overrides": {},
        "categories": [
            1848823525
        ],
        "upselling": [],
        "crossSelling": [],
        "relatedProducts": [],
        "metaTitle": "",
        "metaDescription": "",
        "keywords": [],
        "warranty": "",
        "returnPolicy": "",
        "availability": "in_stock",
        "condition": "new",
        "createdAt": "2025-06-15T12:46:25.101Z",
        "updatedAt": "2025-06-15T12:46:25.102Z",
        "sourceUrl": "https://www.greenlion.net/shop/gnalfrdi130bk-green-lion-alps-fragrance-diffuser-130ml-black-5006",
        "scrapedAt": "2025-06-15T12:46:25.102Z"
    },
    {
        "id": 1239671963,
        "name": "Green Lion Mug Blend Portable Juicer 500ML-White",
        "description": "The Green Lion Mug Blend portable Juicer in beautiful white blends modern style, And that makes it a vital tool for anyone who values comfort and performance. With a two 1500mAh battery and a 70W motor, It works at an amazing speed of 18000 RPM. This compact blender is capable of holding up to 500cc, making it perfect for blending smoothies, shakes, and other drinks. It has an LED indicator, a Type-C charging port, and six powerful blades that can mix up to 15 times on a single charge. Its IPX6 waterproof rating ensures long-lasting durability and ease of maintenance. This Mug Blend portable Juice is stylish and makes it a great option for a busy life. Specification Blade Material: SUS 304Capacity: 500mLBattery Capacity: 1500mAh*2Power: 70WVoltage: DC 7.4VRPM Speed: 18,000 RPMWaterproof: IPX6Charging Port: Type-CCharging Time: 3-4 HoursSingle Blend Time: 40 secBlending Cycles: 10-15 TimesFeatures​40-Sec Quick BlendUp",
        "base_price": 40.53,
        "base_shipping_cost": 0,
        "free_shipping": false,
        "sku": "GNMGBL500WH",
        "gtin": "09904781898980",
        "ean": "",
        "slug": "green-lion-mug-blend-portable-juicer-500ml-white",
        "brand": "Green Lion",
        "rating": 0,
        "reviews_count": 0,
        "status": "active",
        "isFeatured": false,
        "isOnSale": false,
        "requiresShipping": true,
        "requiresInventoryTracking": true,
        "stock": 37,
        "hasVariants": false,
        "totalVariantStock": 0,
        "lowStockThreshold": 5,
        "features": {
            "blade_material": "SUS 304",
            "capacity": "500mL",
            "battery_capacity": "1500mAh*2",
            "power": "70W",
            "voltage": "DC 7.4V",
            "rpm_speed": "18,000 RPM",
            "waterproof": "IPX6",
            "charging_port": "Type-C",
            "charging_time": "3-4 Hours",
            "single_blend_time": "40 sec",
            "blending_cycles": "10-15 Times",
            "40_sec_quick_blend": true,
            "up_to_15_blend_cycles": true,
            "type_c_charging": true,
            "drip_free_spout": true,
            "food_grade_material": true,
            "led_indicator": true,
            "6_blade_powerful": true,
            "high_speed_motor": true
        },
        "images": [
            "products_images/GNMGBL500WH_Green_Lion_Mug_Blend_Portable_Juicer_500ML-White_1.jpg",
            "products_images/GNMGBL500WH_Green_Lion_Mug_Blend_Portable_Juicer_500ML-White_2.jpg"
        ],
        "options": {},
        "option_images": {},
        "variant_images": {},
        "option_variants_stock": {},
        "option_price_adjustments": {},
        "option_shipping_adjustments": {},
        "weight": {},
        "dimensions": {},
        "option_dimension_overrides": {},
        "categories": [
            1810498064
        ],
        "upselling": [],
        "crossSelling": [],
        "relatedProducts": [],
        "metaTitle": "",
        "metaDescription": "",
        "keywords": [],
        "warranty": "",
        "returnPolicy": "",
        "availability": "in_stock",
        "condition": "new",
        "createdAt": "2025-06-15T12:46:27.958Z",
        "updatedAt": "2025-06-15T12:46:27.959Z",
        "sourceUrl": "https://www.greenlion.net/shop/gnmgbl500wh-green-lion-mug-blend-portable-juicer-500ml-white-5004",
        "scrapedAt": "2025-06-15T12:46:27.959Z"
    }];